theme: jekyll-theme-minimal
title: ADA Template Website Leon
description: A template website for ADA Leon
show_downloads: True
navigation:
  - title: example
    url: /
  - title: TaLeCaYu
    url: TaLeCaYu
