theme: jekyll-theme-minimal
title: ADA Template Website Leon
description: A template website for ADA Leon
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
  - title: TaLeCaYu
    url: TaLeCaYu
