theme: jekyll-theme-minimal
title: ADA Template Website Leon
description: A template website for ADA Leon
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: TaLeCaYu
    url: TaLeCaYu
